/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['#googleMapView[_ngcontent-%COMP%]{width:100%}#googleMapView[_ngcontent-%COMP%]   .sebm-google-map-container[_ngcontent-%COMP%]{width:100%;height:300px}/*# sourceMappingURL=undefined.map */'];